// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRg5tuK-l9L-ku2ZUy-Fp1IhWrbh0UAV0',
    appId: '1:532790959654:web:324294958e10c754bd90e7',
    messagingSenderId: '532790959654',
    projectId: 'ecommerce-3b86c',
    authDomain: 'ecommerce-3b86c.firebaseapp.com',
    storageBucket: 'ecommerce-3b86c.appspot.com',
    measurementId: 'G-YQRPTNTNV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXwuoKTOJL0l8W_k6iKvaRvtpiXu7VUq8',
    appId: '1:532790959654:android:1143038bc9bc66e6bd90e7',
    messagingSenderId: '532790959654',
    projectId: 'ecommerce-3b86c',
    storageBucket: 'ecommerce-3b86c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59HiT-zScBb2nvcYJrEEyXIsuWE_ni-k',
    appId: '1:532790959654:ios:e92ea41bf9b01c60bd90e7',
    messagingSenderId: '532790959654',
    projectId: 'ecommerce-3b86c',
    storageBucket: 'ecommerce-3b86c.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59HiT-zScBb2nvcYJrEEyXIsuWE_ni-k',
    appId: '1:532790959654:ios:bff1983f3737a165bd90e7',
    messagingSenderId: '532790959654',
    projectId: 'ecommerce-3b86c',
    storageBucket: 'ecommerce-3b86c.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
